# Generated by Django 4.2.8 on 2023-12-25 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('blog_text', models.TextField(verbose_name='Содержимое')),
                ('blog_preview', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='Превью')),
                ('blog_slug', models.CharField(blank=True, max_length=150, null=True, verbose_name='slug')),
                ('blog_date_creation', models.DateField(auto_now_add=True, verbose_name='Дата публикации')),
                ('blog_is_active', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('blog_views_count', models.IntegerField(default=0, verbose_name='Просмотры')),
                ('blog_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='владелец')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ('blog_title',),
            },
        ),
    ]
